spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qasandbox
    username: qauser
    password: qapass

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html